# Generated by Django 5.0.3 on 2024-04-04 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_rename_agency_addtours_agency'),
        ('customer', '0002_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agency.agencyregistration'),
        ),
    ]
