# Generated by Django 5.0.3 on 2024-04-12 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_rename_agency_addtours_agency'),
        ('customer', '0003_applications_agency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholder', models.TextField(max_length=20, null=True)),
                ('card', models.TextField(max_length=20, null=True)),
                ('cvv', models.TextField(max_length=20, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agency.addtours')),
            ],
        ),
    ]
