# Generated by Django 5.0.3 on 2024-03-28 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agencyregistration',
            table='agency',
        ),
        migrations.CreateModel(
            name='Addtours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Destination', models.TextField(max_length=100, null=True)),
                ('Description', models.TextField(max_length=100, null=True)),
                ('Image', models.ImageField(null=True, upload_to='')),
                ('Charge', models.FloatField(null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.agencyregistration')),
            ],
        ),
    ]
