# Generated by Django 5.0.3 on 2024-03-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_alter_agencyregistration_table_addtours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtours',
            name='Image',
            field=models.ImageField(null=True, upload_to='addtours'),
        ),
    ]
